/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.imdb.query.client.impl;

import static org.junit.jupiter.api.Assertions.assertTrue;

import java.util.Random;

import javax.inject.Inject;

import org.junit.jupiter.api.AfterAll;
import org.junit.jupiter.api.BeforeAll;
import org.junit.jupiter.api.MethodOrderer;
import org.junit.jupiter.api.Order;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.TestInstance;
import org.junit.jupiter.api.TestInstance.Lifecycle;
import org.junit.jupiter.api.TestMethodOrder;

import com.imdb.query.client.ImdbSocketClient;
import com.imdb.query.server.ImdbSocketServer;
import com.imdb.query.server.ServerCommand;
import com.imdb.query.server.impl.ServerCommandImpl;
import com.imdb.query.util.Constants;
import com.imdb.query.util.IMDbQueryModuleInjector;

@TestInstance(Lifecycle.PER_CLASS)
@TestMethodOrder(MethodOrderer.OrderAnnotation.class)
public class ImdbSocketClientImplTest {
    
	@Inject
	private ImdbSocketClient imdbSocketClient;
	
	@Inject
	private ImdbSocketServer imdbSocketServer;

	@BeforeAll
	public void initializeTests() throws InterruptedException {

		// Injetando dependências ...
		
		IMDbQueryModuleInjector.initialize(this);
        
		System.out.println("************ PREPARA SERVIDOR PARA CLIENTE ************");
		System.out.println("");
		
		Thread thread = new Thread(new Runnable() {
		    public void run() {

		    	ServerCommand serverCommand = new ServerCommandImpl();
		    	serverCommand.setImdbSocketServer(imdbSocketServer);
		    	serverCommand.execute();
		    }
		  });
		
        thread.start();
	    thread.join(3000);

		System.out.println("");			
		System.out.println("************ INICA CLIENTE PARA SOLICITAÇÃO NO SERVIDOR ************");
		System.out.println("");			
	}
	
	@Test
    @Order(1)
	public void connectToServerTest() {
		
		boolean connected = imdbSocketClient.connectToServer(Constants.IP_SERVER, Constants.PORT);
		
		assertTrue(connected);
		
		if(connected) {			
			System.out.println("Cliente conectado com o servidor !");
		} else {
			System.out.println("Cliente não conectado com o servidor !");			
		}
	}
	
	@Test
    @Order(2)
	public void sendMovieTitleToSearchInServer() {

		Random random = new Random();
		
		String[] movieArrayTest = 
			{"...E o Vento Levou, ",
	         "12 Anos", 
	         "12 Homens", 
	         "1917, 2001: Uma Odisséia no Espaço", 
	         "3 ", 
	         "A Batalha ", 
	         "A Caça", 
	         "A Chantagem", 
	         "A Criada", 
	         "A Felicidade", 
	         "A General", 
	         "A Lista ", 
	         "A Malvada", 
	         "A Mulher Faz o Homem", 
	         "A Origem", 
	         "A Separação", 
	         "Alien", 
	         "Antes" , 
	         "Batman", 
	         "Um sonho"};
		
		String movieTitleExample = movieArrayTest[random.nextInt(movieArrayTest.length)];

		String sent = imdbSocketClient.sendMovieTitleToSearchInServer(movieTitleExample);

		boolean movieTitleFound = sent != null && !sent.trim().equals("");

		assertTrue(movieTitleFound);
		
		if(movieTitleFound) {			
			System.out.println("Filme(s) encontrado(s): " + movieTitleExample);
		} else {
			System.out.println("Nenhum filme foi encontrado !");			
		}
	}
	
	@AfterAll
	public void stopConnectionTest() {
		
		boolean isClientStopped = imdbSocketClient.stopConnection();
		
		imdbSocketServer.stop();
		
		boolean isServerStopped = imdbSocketServer.isStoped();
		
		assertTrue(isClientStopped && isServerStopped);
		
		if(isClientStopped) {
			System.out.println("Conexão do cliente encerrada !");
		} else {
			System.out.println("Conexão do cliente não encerrada !!!");
		}
		
		if(isServerStopped) {		
			System.out.println("Servidor parado !");	
		} else {
			System.out.println("Servidor não parado !");
		}
	}
}
