/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.imdb.query.client.impl;

import org.junit.Test;
import static org.junit.Assert.*;

public class ImdbSocketClientImplTest {
    
	@Test 
    public void testSomeLibraryMethod() {
       // Library classUnderTest = new Library();
      //  assertTrue("someLibraryMethod should return 'true'", classUnderTest.someLibraryMethod());
    }
}
